plugins:
    - './node_modules/prettier-plugin-astro'
overrides:
    - files: '*.astro'
      options:
          parser: 'astro'
tabWidth: 4
printWidth: 100
semi: false
trailingComma: all
bracketSpacing: true
singleQuote: true
jsxSingleQuote: true
quoteProps: consistent
